version: "3"

services:
  pg:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./.local/postgres
        target: /var/lib/postgresql/data
    env_file: .env
  redis:
    image: bitnami/redis:7.0.12
    ports:
      - 6379:6379
    env_file: .env
    volumes:
      - type: bind
        source: ./.local/redis
        target: /data
